name: "comment-pr"
branding:
  icon: "message-square"
  color: "gray-dark"
description: "Post a dynamic comment on github PullRequests"
inputs:
  GITHUB_TOKEN:
    description: "Github Token for authentication"
    required: true
outputs:
  test-head: # id of output
    description: "head"
  pr-head:
    description: "pr-head"
runs:
  using: "node12"
  main: "dist/index.js"
